all: nif_dll

build: nif_dll

nif_dll:
  if not exist "build" mkdir "build"
  cd build && cmake -G "NMake Makefiles" -DMIX_APP_PATH="$(MIX_APP_PATH)" .. && cmake --build . --config Release && cmake --install . --config Release && cd ..

.PHONY: all
